language: ruby
rvm:
- 2.0.0
before_install:
  - cd RailsTraining/DeilyReportBlog
install:
  - bundle install --without production
script:
  - bundle exec rake db:reset
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - RAILS_ENV=test bundle exec rspec spec/
branches:
  only:
    -master
cache:
  directories:
  - RailsTraining/DailyReportBlog/vendor/bundle
