language: ruby
rvm:
- 2.0.0
env:
  global:
before_install: cd RailsTraining/DeilyReportBlog
install: bundle install --without production --deployment
script: RAILS_ENV=test bundle exec rspec
branches:
  only:
    -master
cache:
  directories:
  - RailsTraining/DailyReportBlog/vendor/bundle
